@startuml

left to right direction
actor NewsAgency as Agency << System >>
actor NewsChannel as Channel << System >>

rectangle "News Delivery" {

    (broadcasts news to NewsCHannels) as broadcasts

    (is notified about news) as notify

    (unsubscribes from NewsAgency) as unsubscribe

    (subscribes to NewsAgency) as subscribe

}

Channel --> subscribe
Channel --> unsubscribe
Channel --> notify

Agency --> broadcast

@enduml